# Generated by Django 2.2.16 on 2023-01-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230108_1845'),
        ('posts', '0005_post_comments'),
    ]

    operations = [
    ]
